### ISSUE TITLE
Features Post

### ISSUE THREAD

**Issue by AlbanMulaki** [PragmaticLinux/web-project#10]
# List of Feature:
## Lightweight or functionality

Simplicity,Fast,rolling Release, Pragmatism, Low Hardware Requirments,  User Friendly, Architecture 64 Bit, Focus Environemnt on Developers and learners,latest cutting-edge software, Elegance, Powerful, Developed on Kosovo, Provides features of arch linux combined with features of pragmatic in order to bring performance, efficiency, Rolling-Release System update, Access to the Arch User Repository(AUR), Pragmatic Aimed at more experienced or technically-minded user, New Installation Process, Can run on old computers, Felxibility, FREE .
## Safe & Secure

Secure OS, No spying, Open source.
## Title:  Web Development

Many Services, Configured for business usage and standalone users,  NetBeans Editor, HTTP(Apache),MySQL(MariaDB), PHP ,Secure Shell - SSH, File Transfer - FTP, Project Manage Structure, For One project you create you have the different environment ,users and password for this project,Frameworks,FileZilla,Chromium, Web Development, Pragmatic-Dev Software, Host Naming, Firefox Developer and normal, Usable as Server, PHPMYADMIN, Port Forwarding customize, Webmin Adminsitration Panel( Web Interface Manage), Also offer new version if you want to self environment for each developer, Pragmatic Linux Server, 
## Title: Environment & Apps

Package Manager Pacman for installation of new software,Thunderbird, FileZilla, Nmap, Firefox Developer, Firefox, Chromium, VLC Player, LibreOffice, Chromium, GIT, XFCE4 Desktop, Frameworks, PHP(Laravel, CodeIgniter, Yii-Basic ...), Javascript (Backbone,AngularJS....), HTML(Bootstrap,Foundation 4, 99lime ....) and more, Sublimte Text Editor, BitTorrent Client, Team Viewer, XChat IRC, UNetBootin, Oracle Virtual Machine, Partition Editor Manager GUI, GRUB Bootloader, Pragmatic-Dev Software.
## Pragmatic Linux Server

Its different version by Pragmatic Linux, Offer minimalist usage of Memory,CPU and Disk Space, Pragmatic Linux Server is designed for System Adminsitrator to build infrastructure of network, Also this can be used as standalone via virtualbox, it can act liek web server, which is compatibile with every OS, MAC,Windows,Linux via virtuallbox installed, then take the machine, PortForwarding posibility, start many instance of server, in one Real Machine, services offers - Apache,MySQL,PHP,FTP,SSH,SMB Share, Webmin Adminsitration Panel Web Interface, phpmyadmin, Portforwarding.Configured environemnt, Hostname,

**Comment by AlbanMulaki** [comment]
For each Feature write also an short more short description which can be used to show on front page.

**Comment by albansejdiu** [comment]
Here are the features and short descriptions. **I recommend that you read all of them carefully**. Some things may require editing.

[Feature-Post.docx](https://github.com/PragmaticLinux/web-project/files/490720/Feature-Post.docx)

**Comment by AlbanMulaki** [comment]
It has been finished
