### ISSUE TITLE
Insert photo into Home page

### ISSUE THREAD

**Issue by albansejdiu** [PragmaticLinux/web-project#13]
Insert photos of Pragmatic Linux use in everyday life. For example:
https://www.microsoft.com/en-us/windows/get-windows-10

**Comment by AlbanMulaki** [comment]
![pragmatic linux web development](https://cloud.githubusercontent.com/assets/9609237/18797449/4a1a4348-81ce-11e6-83a6-13150f87ceee.png)

**Comment by AlbanMulaki** [comment]
#15

**Comment by albansejdiu** [comment]
My feedback: It looks great! I like it.
