### ISSUE TITLE
For business Page

### ISSUE THREAD

**Issue by AlbanMulaki** [PragmaticLinux/web-project#18]
### Intranet

> **Icon:** Choose an icon
> Used in intranet, Access projects via url from another computer which is connected to this intranet,Shareable, Git Server, Have user for each project, isolation environment for projects,
### Fast Development

> **Icon:** Choose an icon
> Software Pragmatic-dev, fast initialization of projects, easy installation of frameworks, easy to get every framework with latest version,handle server via ssh from remote.
### Ready Environment

> **Icon:** Choose an icon
> Optimized environment for developers, if interested in environment for server go ahed Pragmatic Linux Server, Comes with less usage of memory, GPU and CPU, XFCE Desktop, Tools (NetBeans,Git,composer, PHP5.6, PHP7, MySQL, FTP, SSH, Apache, Bootloader, Installation ....)
### Capable in VirtualBox

> **Icon:** Choose an icon
> Capable to use as server in virtualbox, manage from virtualbox, Access from other computer on network (intranet), use Domain Name instead of IP, configure VirtualHost by router, Allocate memory,cpu Cores, HDD in virtualbox, Easy to install, Easy to configure and start to use as server.
### Server Role

> **Icon:** Choose an icon
> Role as FTP Server, SSH Server, Web Hosting, MySQL Database, Administration Panel Webmin, processing PHP, Fast Boot, Auto Correction error, Easy Manage.

**Comment by albansejdiu** [comment]
Content is nearly finished. The text marked in red needs to be discussed and maybe edited (see attached file). Feedback required. 

[For business page - 18.docx](https://github.com/PragmaticLinux/web-project/files/501702/For.business.page.-.18.docx)

**Comment by AlbanMulaki** [comment]
Intranet - Done
Fast Development - Done
Ready Environment - Done
Capable in VirtualBox - Done

**Comment by albansejdiu** [comment]
[For.business.page.-.18.docx](https://github.com/PragmaticLinux/web-project/files/511563/For.business.page.-.18.docx)
