### ISSUE TITLE
Get Help Page

### ISSUE THREAD

**Issue by AlbanMulaki** [PragmaticLinux/web-project#20]
Split on 4 column, and write services that pragmatic linux website and community offers. one for each column.
## Community Forum

> Icon from font-awesome
> Community,Pragmatic Linux, Forum, Documentation, Help others, ask your question 
## FAQs

> Icon from font-awesome
> Quick question, check, frequently,
## Report a Bug

> Icon from font-awesome
> Found bug, report, suggestion,is done, post it, report it.
## Video Walkthrough

> Icon from font-awesome
> Walkthrough, basic task, setting up, installing, Subscribe youtube channel,
## Documentation Wiki

> Icon from font-awesome
> Get official documentation,manual,usage,how to, guides

**Comment by AlbanMulaki** [comment]
## Get Involved

> Icon from font-awesome
> email: getinvolved@pragmaticlinux.org, involved Collaborate,

## Collaborate

> Icon from font-awesome
> Email: info@pragmaticlinux.org, Collaborate with us, projects, Software Development, linux, sys admin,

**Comment by AlbanMulaki** [comment]
## Participate in events

> Icon from font-awesome
> Organize, participate, contribute, presentation

**Comment by albansejdiu** [comment]
Here's the content. Feedback needed.

[Get Help Page #20.docx](https://github.com/PragmaticLinux/web-project/files/531080/Get.Help.Page.20.docx)

**Comment by AlbanMulaki** [comment]
http://dev.pragmaticlinux.org/get-help/
