### ISSUE TITLE
Frequently Ask and Question - FAQ

### ISSUE THREAD

**Issue by AlbanMulaki** [PragmaticLinux/web-project#21]
If somewhere its needed any link would be great to make them with blue color
## What is Pragmatic linux ?

Dedicated to software developer, designed for developer, system administrator, offers huge of tools, many services, ready environment.
## Where i can use it?

In business, Home, Self, Development Software, Server, System Administration, Git Server, FTP Server, SSH Server,Database, Virtual Box
## Why would i use Pragmatic Linux ?

Benefit,Many projects can be managed,Easy of use, Easy maintenance, acces via intrantet, collaborate with team, git server, client, public server, Web Hosting
## What else can i do with Pragmatic Linux ?

Pragmatic Linux offers same also third party from Arch Linux. 
## Why Pragmatic Linux is only 64 Bit ?

Requires 64 bit Process,Memory not support by 32 Bit, Accept more memory, offers better resources.
## What are the hardware requirments for pragmatic linux ?

Depends very strongly on what you plan, dedicated page for hardware, plan to use.
## Where i can get Help ?

Forum,Wiki,Documentation,youtube channel

**Comment by albansejdiu** [comment]
Need feedback for highlighted text.

[Frequently Ask and Question - FAQ #21.docx](https://github.com/PragmaticLinux/web-project/files/532108/Frequently.Ask.and.Question.-.FAQ.21.docx)

**Comment by AlbanMulaki** [comment]
[Frequently.Ask.and.Question.-.FAQ-updated.docx](https://github.com/PragmaticLinux/web-project/files/535764/Frequently.Ask.and.Question.-.FAQ-updated.docx)
