### ISSUE TITLE
Partners and Friends Page

### ISSUE THREAD

**Issue by AlbanMulaki** [PragmaticLinux/web-project#22]
For Each Partner show short description, and show logo of them.
## Vizioni Per Arsim - VPA

URL:www.vpa-uni.com
Education,Computer Science, College,Server , Network Infrastructure, Laborator, Usage, Comfortable.
## Riba Linux

Portal, News, Information, Technology, How To
## Llampa

URL:www.llampa.com
Software Development, Web Development, Training, Business Analysis, High Quality,Leadership
## Linux Foundation

Licensed by Linux foundation,Access to use Linux Word right reserved
## Open Invention Network - OIN Community

Protect License,http://www.openinventionnetwork.com/community-of-licensees/,

**Comment by AlbanMulaki** [comment]
![1](https://cloud.githubusercontent.com/assets/9609237/18601761/47131a30-7c65-11e6-89d3-02f7714ceeb0.png)
![2](https://cloud.githubusercontent.com/assets/9609237/18601762/471a23d4-7c65-11e6-9848-285436d19c1d.png)
![3](https://cloud.githubusercontent.com/assets/9609237/18601763/472a87f6-7c65-11e6-8133-af9f230fd4e8.png)
![4](https://cloud.githubusercontent.com/assets/9609237/18601764/4733db9e-7c65-11e6-83c6-0ecd7c84c368.png)
![5](https://cloud.githubusercontent.com/assets/9609237/18601765/4739d80a-7c65-11e6-93de-456aabed5290.png)

**Comment by albansejdiu** [comment]
NO NEED FOR TEXT!
