### ISSUE TITLE
Video Page

### ISSUE THREAD

**Issue by AlbanMulaki** [PragmaticLinux/web-project#23]
Take Video Youtube from Channel Pragmatic Linux and put on Pragmatic Linux Website

**Comment by AlbanMulaki** [comment]
@albansejdiu Do UAT, and comment feedback or any changes that is needed to be made.

**Comment by albansejdiu** [comment]
1. Show video length in video name, ex. "video 1 (14:32)".
2. Add two main categories "Pragmatic Linux" and "Pragmatic Linux Server", each has its own list with videos (shows after click).
