### ISSUE TITLE
Team Page

### ISSUE THREAD

**Issue by AlbanMulaki** [PragmaticLinux/web-project#24]
**Active Member:** 
Alban Mulaki: Founder, Developer, Programmer
Meriton Salihu: Logo and Artwork Designer
Alban Sejdiu: Director Content

**Non Active Member**
Riad Ibrahimi: Consultant
Faton Nuha: Forum Maintainer

**Comment by AlbanMulaki** [comment]
Just Active Member Added at Team Page

**Comment by AlbanMulaki** [comment]
@albansejdiu Do UAT, and comment feedback or any changes that is needed to be made.

**Comment by albansejdiu** [comment]
Change: "Since 2016 Active" to "Active since 2016", "Software Developer C#" to "Software Developer", "Director Content" to "Content Director".
Include not active members with grey or orange status color.
