### ISSUE TITLE
Donate Pages

### ISSUE THREAD

**Issue by AlbanMulaki** [PragmaticLinux/web-project#25]
Survives, community, core development, no paid for our works, many way to support (technical development, documentation, maintain forum,good at python, bash, money, donate, java, grub, Linux System, ... ), Non-Profit, organisation, hosting, pay, purchase, equipment, contribute
## Why donate ?

Free,income, funded, sponsors, donations, community users.
## How is the money used?

Money,finance,hosting, maintain,resources,equipment

Donate via Credit Card VISA, send mail donate@pragmaticlinux.org and amulaki@pragmaticlinux.org

![image](https://cloud.githubusercontent.com/assets/9609237/18568004/2d0c55b8-7b9b-11e6-8ed5-8a662b4e2c55.png)

Account Holder: Alban Mulaki

Name of Beneficary Bank: Banka Ekonomike Sh.a

SWIFT Code: EKOMXKPRXXX

Bank Address: Sheshi “Nena Tereze”, nn, Prishtina, Kosova

IBAN: XK05 14070 000 0669 4140

Currency: Euro (USD,CHF)

![image](https://cloud.githubusercontent.com/assets/9609237/18568014/3efb9176-7b9b-11e6-9e9c-b838b58b79cb.png)

Account Holder: Alban Mulaki

Name of Beneficary Bank: Raiffeisen Bank Kosovo

SWIFT Code: RBKOXKPR

Bank Address: Prishtina, Kosovo

IBAN: XK05 14070 000 0669 4140

Currency: Euro (GBP,USD,CHF,DKK,CAD,SEK,NOK)

**Comment by AlbanMulaki** [comment]
[Donate-Pages-25.docx](https://github.com/PragmaticLinux/web-project/files/547164/Donate-Pages-25.docx)

**Comment by albansejdiu** [comment]
Nearly done!

[Uploading Donate-Pages-25.docx…]()

**Comment by albansejdiu** [comment]
Nearly done!

[Donate-Pages-25.docx](https://github.com/PragmaticLinux/web-project/files/547285/Donate-Pages-25.docx)

**Comment by AlbanMulaki** [comment]
[Donate-Pages-25 final.docx](https://github.com/PragmaticLinux/web-project/files/547293/Donate-Pages-25.final.docx)
