### ISSUE TITLE
Content Of Website, two first block

### ISSUE THREAD

**Issue by AlbanMulaki** [PragmaticLinux/web-project#9]
**Left Block:**
**Title:** What is Pragmatic Linux ?
**Text Keywords:** Web Development, Server Environment, Fast & Lightweight, Stable,Services,Based on arch linux,64 Bit,Licensed, Tools, Web Server.

**Right Block**
**Title:** What is for?
**Text Keywords:** Software Developer,Web Developer, Server Administrator, Easy manage of projects,Easy to use, Free, Business Use, Internal Server Network.

![screenshot - 2016-sht-14 - 09 11 15 cest](https://cloud.githubusercontent.com/assets/9609237/18503054/341cc81a-7a5b-11e6-9b7e-17bc2b40fd59.png)

**Comment by albansejdiu** [comment]
[Content Of Website, two first block #9.docx](https://github.com/PragmaticLinux/web-project/files/472538/Content.Of.Website.two.first.block.9.docx)
